# Generated by Django 5.0.1 on 2025-11-01 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LichSuTimKiem",
            fields=[
                (
                    "maTimKiem",
                    models.AutoField(
                        db_column="maTimKiem", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tuKhoa",
                    models.CharField(
                        db_column="tuKhoa", max_length=255, verbose_name="từ khóa"
                    ),
                ),
                (
                    "ngayTim",
                    models.DateTimeField(
                        auto_now_add=True, db_column="ngayTim", verbose_name="ngày tìm"
                    ),
                ),
                (
                    "soKetQua",
                    models.IntegerField(
                        db_column="soKetQua", default=0, verbose_name="số kết quả"
                    ),
                ),
                (
                    "maDiaDiem",
                    models.ForeignKey(
                        blank=True,
                        db_column="maDiaDiem",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tim_kiems",
                        to="places.diadiem",
                        verbose_name="địa điểm",
                    ),
                ),
                (
                    "maNguoiDung",
                    models.ForeignKey(
                        db_column="maNguoiDung",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lich_su_tim_kiems",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử tìm kiếm",
                "verbose_name_plural": "Lịch sử tìm kiếm",
                "db_table": "LICHSU_TIMKIEM",
                "ordering": ["-ngayTim"],
                "indexes": [
                    models.Index(
                        fields=["maNguoiDung", "-ngayTim"],
                        name="LICHSU_TIMK_maNguoi_38043d_idx",
                    )
                ],
            },
        ),
    ]
