# Generated by Django 5.0.1 on 2026-06-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lichsutimkiem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lichsutimkiem',
            new_name='LICHSU_TIMK_maNguoi_38043d_idx',
            old_name='LICHSUTIMK_maNguo_f5a0f9_idx',
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='username',
            field=models.CharField(db_column='tenDangNhap', help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='tên đăng nhập'),
        ),
    ]
