# Generated by Django 5.0.1 on 2025-11-24 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('maHang', models.AutoField(db_column='maHang', primary_key=True, serialize=False)),
                ('tenHang', models.CharField(db_column='tenHang', max_length=255, unique=True, verbose_name='tên hãng')),
                ('maIATA', models.CharField(blank=True, db_column='maIATA', help_text='Ví dụ: VN, VJ, BL', max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='Mã IATA hãng phải là 2 ký tự', regex='^[A-Z0-9]{2}$')], verbose_name='mã IATA')),
                ('logo', models.CharField(blank=True, db_column='logo', max_length=500, verbose_name='logo')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
            ],
            options={
                'verbose_name': 'Hãng hàng không',
                'verbose_name_plural': 'Hãng hàng không',
                'db_table': 'HANGHANGKHONG',
                'ordering': ['tenHang'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('maSanBay', models.AutoField(db_column='maSanBay', primary_key=True, serialize=False)),
                ('tenSanBay', models.CharField(db_column='tenSanBay', max_length=255, verbose_name='tên sân bay')),
                ('maIATA', models.CharField(db_column='maIATA', help_text='Ví dụ: SGN, HAN, DAD', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Mã IATA phải là 3 chữ cái in hoa', regex='^[A-Z]{3}$')], verbose_name='mã IATA')),
                ('maICAO', models.CharField(blank=True, db_column='maICAO', max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Mã ICAO phải là 4 chữ cái in hoa', regex='^[A-Z]{4}$')], verbose_name='mã ICAO')),
                ('diaChi', models.CharField(blank=True, db_column='diaChi', max_length=500, verbose_name='địa chỉ')),
                ('viDo', models.FloatField(blank=True, db_column='viDo', null=True, verbose_name='vĩ độ')),
                ('kinhDo', models.FloatField(blank=True, db_column='kinhDo', null=True, verbose_name='kinh độ')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
                ('lanCapNhatCuoi', models.DateTimeField(auto_now=True, db_column='lanCapNhatCuoi', verbose_name='lần cập nhật cuối')),
            ],
            options={
                'verbose_name': 'Sân bay',
                'verbose_name_plural': 'Sân bay',
                'db_table': 'SANBAY',
                'ordering': ['tenSanBay'],
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('maLichChuyen', models.AutoField(db_column='maLichChuyen', primary_key=True, serialize=False)),
                ('loaiChuyen', models.CharField(choices=[('departure', 'Khởi hành'), ('arrival', 'Đến')], db_column='loaiChuyen', max_length=20, verbose_name='loại chuyến')),
                ('ngayBay', models.DateField(db_column='ngayBay', verbose_name='ngày bay')),
                ('gioKeHoach', models.TimeField(db_column='gioKeHoach', help_text='Scheduled time', verbose_name='giờ kế hoạch')),
                ('gioCapNhat', models.TimeField(blank=True, db_column='gioCapNhat', help_text='Updated/Estimated time', null=True, verbose_name='giờ cập nhật')),
                ('loTrinh', models.CharField(db_column='loTrinh', help_text='Ví dụ: SGN-HAN, HAN-DAD', max_length=20, verbose_name='lộ trình')),
                ('soHieuChuyen', models.CharField(db_column='soHieuChuyen', db_index=True, help_text='Flight number, ví dụ: VN123, VJ456', max_length=20, verbose_name='số hiệu chuyến')),
                ('quay', models.CharField(blank=True, db_column='quay', help_text='Check-in counter', max_length=50, verbose_name='quầy')),
                ('cong', models.CharField(blank=True, db_column='cong', help_text='Gate', max_length=50, verbose_name='cổng')),
                ('sanh', models.CharField(blank=True, db_column='sanh', help_text='Terminal', max_length=50, verbose_name='sảnh')),
                ('trangThai', models.CharField(choices=[('scheduled', 'Theo lịch'), ('delayed', 'Hoãn'), ('boarding', 'Đang lên máy bay'), ('departed', 'Đã khởi hành'), ('arrived', 'Đã đến'), ('cancelled', 'Hủy'), ('unknown', 'Không xác định')], db_column='trangThai', default='scheduled', max_length=20, verbose_name='trạng thái')),
                ('ghiChu', models.TextField(blank=True, db_column='ghiChu', verbose_name='ghi chú')),
                ('thoiGianThuThap', models.DateTimeField(auto_now_add=True, db_column='thoiGianThuThap', help_text='Crawled time', verbose_name='thời gian thu thập')),
                ('lanCapNhatCuoi', models.DateTimeField(auto_now=True, db_column='lanCapNhatCuoi', verbose_name='lần cập nhật cuối')),
                ('maHang', models.ForeignKey(blank=True, db_column='maHang', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lich_chuyen_bays', to='flights.airline', verbose_name='hãng hàng không')),
                ('maSanBay', models.ForeignKey(db_column='maSanBay', on_delete=django.db.models.deletion.PROTECT, related_name='lich_chuyen_bays', to='flights.airport', verbose_name='sân bay')),
            ],
            options={
                'verbose_name': 'Lịch chuyến bay',
                'verbose_name_plural': 'Lịch chuyến bay',
                'db_table': 'LICHCHUYENBAY',
                'ordering': ['-ngayBay', 'gioKeHoach'],
                'indexes': [models.Index(fields=['-ngayBay', 'gioKeHoach'], name='LICHCHUYENB_ngayBay_53c1a9_idx'), models.Index(fields=['maSanBay', 'loaiChuyen'], name='LICHCHUYENB_maSanBa_dcdc76_idx'), models.Index(fields=['soHieuChuyen'], name='LICHCHUYENB_soHieuC_c94dc0_idx'), models.Index(fields=['maHang'], name='LICHCHUYENB_maHang_34f9f0_idx')],
            },
        ),
    ]
