"""
Test script để tạo lịch trình và generate description bằng LLM
"""
import os
import sys
import django
import asyncio
import json
from pathlib import Path

# Setup Django
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'vivu_core.settings')
django.setup()

from agents.travel_agents.orchestrator_agent import OrchestratorAgent
from utils.itinerary_formatter import format_state_to_json, generate_itinerary_description

async def create_itinerary():
    """Tạo lịch trình và generate description"""
    
    print("=" * 80)
    print("TẠO LỊCH TRÌNH: Vũng Tàu → Đà Nẵng (3 ngày, 2 người, danh lam thắng cảnh)")
    print("=" * 80)
    
    # Prepare state
    state = {
        'origin': 'Vũng Tàu',
        'destination': 'Đà Nẵng',
        'start_date': '2025-12-15',
        'days': 3,
        'travelers': 2,
        'travel_style': 'danh_lam_thang_canh',  # Phong cách danh lam thắng cảnh
        'interests': ['danh lam thắng cảnh', 'thiên nhiên', 'phong cảnh'],
        'rooms': 1
    }
    
    print("\n📋 Thông tin lịch trình:")
    print(f"  Điểm xuất phát: {state['origin']}")
    print(f"  Điểm đến: {state['destination']}")
    print(f"  Số ngày: {state['days']}")
    print(f"  Số người: {state['travelers']}")
    print(f"  Phong cách: {state['travel_style']}")
    print(f"  Ngày bắt đầu: {state['start_date']}")
    
    print("\n🔄 Đang tạo lịch trình với Orchestrator Agent...")
    print("-" * 80)
    
    # Execute orchestrator
    orchestrator = OrchestratorAgent()
    result_state = await orchestrator.execute(state)
    
    if result_state.get('status') == 'error':
        print(f"❌ Lỗi: {result_state.get('error', 'Unknown error')}")
        return
    
    print("✅ Lịch trình đã được tạo thành công!")
    
    # Format to JSON
    print("\n📦 Đang format thành JSON structure...")
    print("-" * 80)
    json_data = format_state_to_json(result_state)
    
    # Save JSON to file
    json_file = PROJECT_ROOT / 'scripts' / 'itinerary_output.json'
    with open(json_file, 'w', encoding='utf-8') as f:
        json.dump(json_data, f, ensure_ascii=False, indent=2)
    print(f"✅ Đã lưu JSON vào: {json_file}")
    
    # Display JSON
    print("\n" + "=" * 80)
    print("📄 JSON DATA:")
    print("=" * 80)
    print(json.dumps(json_data, ensure_ascii=False, indent=2))
    
    # Generate description using LLM
    print("\n" + "=" * 80)
    print("🤖 Đang generate mô tả bằng LLM...")
    print("-" * 80)
    
    try:
        description = generate_itinerary_description(json_data, force_llm=True)
        
        # Save description to file
        desc_file = PROJECT_ROOT / 'scripts' / 'itinerary_description.txt'
        with open(desc_file, 'w', encoding='utf-8') as f:
            f.write(description)
        print(f"✅ Đã lưu mô tả vào: {desc_file}")
        
        # Display description
        print("\n" + "=" * 80)
        print("📝 MÔ TẢ LỊCH TRÌNH (Generated by LLM):")
        print("=" * 80)
        print(description)
        
    except Exception as e:
        print(f"❌ Lỗi khi generate description: {e}")
        import traceback
        traceback.print_exc()
    
    # Summary
    print("\n" + "=" * 80)
    print("📊 TÓM TẮT:")
    print("=" * 80)
    print(f"  Tổng chi phí ước tính: {result_state.get('total_cost', 0):,} VNĐ")
    print(f"  Số địa điểm: {len(json_data.get('DIADIEM', []))}")
    print(f"  Số điểm tham quan: {len(json_data.get('LICHTRINH_DIADIEM', []))}")
    
    if result_state.get('itinerary'):
        itinerary = result_state['itinerary']
        if isinstance(itinerary, dict) and 'itinerary' in itinerary:
            print(f"  Số ngày có lịch trình: {len(itinerary['itinerary'])}")
    
    print("\n✅ Hoàn thành!")

if __name__ == "__main__":
    asyncio.run(create_itinerary())



