# Generated by Django 5.2.7 on 2025-10-29 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('maDanhGia', models.AutoField(db_column='maDanhGia', primary_key=True, serialize=False)),
                ('diemDanhGia', models.IntegerField(db_column='diemDanhGia', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='điểm đánh giá')),
                ('tieuDe', models.CharField(blank=True, db_column='tieuDe', max_length=255, verbose_name='tiêu đề')),
                ('noiDung', models.TextField(db_column='noiDung', verbose_name='nội dung')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
                ('lanCapNhatCuoi', models.DateTimeField(auto_now=True, db_column='lanCapNhatCuoi', verbose_name='lần cập nhật cuối')),
                ('soLuotThich', models.IntegerField(db_column='soLuotThich', default=0, verbose_name='số lượt thích')),
                ('trangThai', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('flagged', 'Flagged')], db_column='trangThai', default='active', max_length=20, verbose_name='trạng thái')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'db_table': 'DANHGIA',
                'ordering': ['-ngayTao'],
            },
        ),
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('maDiaDiem', models.AutoField(db_column='maDiaDiem', primary_key=True, serialize=False)),
                ('tenDiaDiem', models.CharField(db_column='tenDiaDiem', db_index=True, max_length=255, verbose_name='tên địa điểm')),
                ('moTa', models.TextField(blank=True, db_column='moTa', verbose_name='mô tả')),
                ('diaChi', models.CharField(blank=True, db_column='diaChi', max_length=500, verbose_name='địa chỉ')),
                ('loaiDiaDiem', models.CharField(choices=[('dia_danh', 'Địa danh'), ('nha_hang', 'Nhà hàng'), ('khach_san', 'Khách sạn'), ('giai_tri', 'Giải trí'), ('mua_sam', 'Mua sắm'), ('khac', 'Khác')], db_column='loaiDiaDiem', max_length=50, verbose_name='loại địa điểm')),
                ('viDo', models.FloatField(blank=True, db_column='viDo', null=True, verbose_name='vĩ độ')),
                ('kinhDo', models.FloatField(blank=True, db_column='kinhDo', null=True, verbose_name='kinh độ')),
                ('giaVe', models.FloatField(blank=True, db_column='giaVe', null=True, verbose_name='giá vé')),
                ('gioMoCua', models.CharField(blank=True, db_column='gioMoCua', max_length=50, verbose_name='giờ mở cửa')),
                ('gioDongCua', models.CharField(blank=True, db_column='gioDongCua', max_length=50, verbose_name='giờ đóng cửa')),
                ('dienThoai', models.CharField(blank=True, db_column='dienThoai', max_length=20, verbose_name='điện thoại')),
                ('website', models.URLField(blank=True, db_column='website', verbose_name='website')),
                ('danhGiaTrungBinh', models.FloatField(db_column='danhGiaTrungBinh', default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='đánh giá trung bình')),
                ('soLuotDanhGia', models.IntegerField(db_column='soLuotDanhGia', default=0, verbose_name='số lượt đánh giá')),
                ('soLuotXem', models.IntegerField(db_column='soLuotXem', default=0, verbose_name='số lượt xem')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
                ('lanCapNhatCuoi', models.DateTimeField(auto_now=True, db_column='lanCapNhatCuoi', verbose_name='lần cập nhật cuối')),
                ('trangThai', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], db_column='trangThai', default='active', max_length=20, verbose_name='trạng thái')),
                ('dacDiem', models.TextField(blank=True, db_column='dacDiem', help_text='JSON string for special features', verbose_name='đặc điểm (JSON)')),
                ('tienNghi', models.TextField(blank=True, db_column='tienNghi', help_text='JSON string for amenities', verbose_name='tiện nghi (JSON)')),
            ],
            options={
                'verbose_name': 'Địa điểm',
                'verbose_name_plural': 'Địa điểm',
                'db_table': 'DIADIEM',
                'ordering': ['-danhGiaTrungBinh', '-soLuotDanhGia'],
            },
        ),
        migrations.CreateModel(
            name='DiaDiemYeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayThem', models.DateTimeField(auto_now_add=True, db_column='ngayThem', verbose_name='ngày thêm')),
                ('ghiChu', models.TextField(blank=True, db_column='ghiChu', verbose_name='ghi chú')),
            ],
            options={
                'verbose_name': 'Địa điểm yêu thích',
                'verbose_name_plural': 'Địa điểm yêu thích',
                'db_table': 'DIADIEM_YEUTHICH',
                'ordering': ['-ngayThem'],
            },
        ),
        migrations.CreateModel(
            name='HinhAnhDiaDiem',
            fields=[
                ('maHinhAnh', models.AutoField(db_column='maHinhAnh', primary_key=True, serialize=False)),
                ('urlHinhAnh', models.CharField(db_column='urlHinhAnh', max_length=500, verbose_name='URL hình ảnh')),
                ('moTa', models.CharField(blank=True, db_column='moTa', max_length=500, verbose_name='mô tả')),
                ('laChinh', models.BooleanField(db_column='laChinh', default=False, verbose_name='là chính')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
            ],
            options={
                'verbose_name': 'Hình ảnh địa điểm',
                'verbose_name_plural': 'Hình ảnh địa điểm',
                'db_table': 'HINHANHDIADIEM',
                'ordering': ['-laChinh', '-ngayTao'],
            },
        ),
        migrations.CreateModel(
            name='TinhThanh',
            fields=[
                ('maTinhThanh', models.AutoField(db_column='maTinhThanh', primary_key=True, serialize=False)),
                ('tenTinhThanh', models.CharField(db_column='tenTinhThanh', db_index=True, max_length=255, unique=True, verbose_name='tên tỉnh thành')),
                ('moTa', models.TextField(blank=True, db_column='moTa', verbose_name='mô tả')),
                ('anhDaiDien', models.CharField(blank=True, db_column='anhDaiDien', max_length=500, verbose_name='ảnh đại diện')),
                ('viDo', models.FloatField(blank=True, db_column='viDo', null=True, verbose_name='vĩ độ')),
                ('kinhDo', models.FloatField(blank=True, db_column='kinhDo', null=True, verbose_name='kinh độ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật')),
            ],
            options={
                'verbose_name': 'Tỉnh thành',
                'verbose_name_plural': 'Tỉnh thành',
                'db_table': 'TINHTHANH',
                'ordering': ['tenTinhThanh'],
            },
        ),
    ]
