# Generated by Django 5.2.7 on 2025-10-29 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='maNguoiDung',
            field=models.ForeignKey(db_column='maNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='danh_gias', to=settings.AUTH_USER_MODEL, verbose_name='người dùng'),
        ),
        migrations.AddField(
            model_name='diadiem',
            name='maNguoiTao',
            field=models.ForeignKey(blank=True, db_column='maNguoiTao', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dia_diems_created', to=settings.AUTH_USER_MODEL, verbose_name='người tạo'),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='maDiaDiem',
            field=models.ForeignKey(db_column='maDiaDiem', on_delete=django.db.models.deletion.CASCADE, related_name='danh_gias', to='places.diadiem', verbose_name='địa điểm'),
        ),
        migrations.AddField(
            model_name='diadiemyeuthich',
            name='maDiaDiem',
            field=models.ForeignKey(db_column='maDiaDiem', on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_dungs_yeu_thich', to='places.diadiem', verbose_name='địa điểm'),
        ),
        migrations.AddField(
            model_name='diadiemyeuthich',
            name='maNguoiDung',
            field=models.ForeignKey(db_column='maNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='dia_diems_yeu_thich', to=settings.AUTH_USER_MODEL, verbose_name='người dùng'),
        ),
        migrations.AddField(
            model_name='hinhanhdiadiem',
            name='maDiaDiem',
            field=models.ForeignKey(db_column='maDiaDiem', on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anhs', to='places.diadiem', verbose_name='địa điểm'),
        ),
        migrations.AddField(
            model_name='diadiem',
            name='maTinhThanh',
            field=models.ForeignKey(db_column='maTinhThanh', on_delete=django.db.models.deletion.CASCADE, related_name='dia_diems', to='places.tinhthanh', verbose_name='tỉnh thành'),
        ),
        migrations.AddIndex(
            model_name='danhgia',
            index=models.Index(fields=['maDiaDiem', '-ngayTao'], name='DANHGIA_maDiaDi_716023_idx'),
        ),
        migrations.AddIndex(
            model_name='danhgia',
            index=models.Index(fields=['maNguoiDung'], name='DANHGIA_maNguoi_d4a0f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='danhgia',
            unique_together={('maDiaDiem', 'maNguoiDung')},
        ),
        migrations.AlterUniqueTogether(
            name='diadiemyeuthich',
            unique_together={('maNguoiDung', 'maDiaDiem')},
        ),
        migrations.AddIndex(
            model_name='hinhanhdiadiem',
            index=models.Index(fields=['maDiaDiem'], name='HINHANHDIAD_maDiaDi_7a3971_idx'),
        ),
        migrations.AddIndex(
            model_name='diadiem',
            index=models.Index(fields=['maTinhThanh', 'loaiDiaDiem'], name='DIADIEM_maTinhT_58a390_idx'),
        ),
        migrations.AddIndex(
            model_name='diadiem',
            index=models.Index(fields=['-danhGiaTrungBinh'], name='DIADIEM_danhGia_14da23_idx'),
        ),
        migrations.AddIndex(
            model_name='diadiem',
            index=models.Index(fields=['trangThai'], name='DIADIEM_trangTh_290f7b_idx'),
        ),
    ]
