# Generated by Django 5.0.1 on 2026-06-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='yeucaulotrinh',
            new_name='YEUCAULOTRI_loaiYeu_cb84ef_idx',
            old_name='YEUCAULOTR_loaiYe_33eef0_idx',
        ),
        migrations.RenameIndex(
            model_name='yeucaulotrinh',
            new_name='YEUCAULOTRI_trangTh_f01c3c_idx',
            old_name='YEUCAULOTR_trangT_7a530e_idx',
        ),
        migrations.RenameIndex(
            model_name='yeucaulotrinh',
            new_name='YEUCAULOTRI_maNguoi_4f1289_idx',
            old_name='YEUCAULOTR_maNguo_c1b4b9_idx',
        ),
        migrations.RenameIndex(
            model_name='yeucaulotrinh',
            new_name='YEUCAULOTRI_maTinhT_e08ce6_idx',
            old_name='YEUCAULOTR_maTinh_b9f541_idx',
        ),
    ]
