# Generated by Django 5.2.7 on 2025-10-29 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DongGop',
            fields=[
                ('maDongGop', models.AutoField(db_column='maDongGop', primary_key=True, serialize=False)),
                ('loaiDongGop', models.CharField(choices=[('them_dia_diem', 'Thêm địa điểm'), ('sua_thong_tin', 'Sửa thông tin'), ('bao_cao_loi', 'Báo cáo lỗi'), ('khac', 'Khác')], db_column='loaiDongGop', max_length=50, verbose_name='loại đóng góp')),
                ('noiDung', models.TextField(db_column='noiDung', verbose_name='nội dung')),
                ('trangThai', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_column='trangThai', default='pending', max_length=20, verbose_name='trạng thái')),
                ('phanHoi', models.TextField(blank=True, db_column='phanHoi', verbose_name='phản hồi')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
                ('ngayXuLy', models.DateTimeField(blank=True, db_column='ngayXuLy', null=True, verbose_name='ngày xử lý')),
            ],
            options={
                'verbose_name': 'Đóng góp',
                'verbose_name_plural': 'Đóng góp',
                'db_table': 'DONGGOP',
                'ordering': ['-ngayTao'],
            },
        ),
        migrations.CreateModel(
            name='LichTrinh',
            fields=[
                ('maLichTrinh', models.AutoField(db_column='maLichTrinh', primary_key=True, serialize=False)),
                ('tieuDe', models.CharField(db_column='tieuDe', max_length=255, verbose_name='tiêu đề')),
                ('moTa', models.TextField(blank=True, db_column='moTa', verbose_name='mô tả')),
                ('ngayBatDau', models.DateField(db_column='ngayBatDau', verbose_name='ngày bắt đầu')),
                ('ngayKetThuc', models.DateField(db_column='ngayKetThuc', verbose_name='ngày kết thúc')),
                ('soNgay', models.IntegerField(blank=True, db_column='soNgay', null=True, verbose_name='số ngày')),
                ('soNguoi', models.IntegerField(db_column='soNguoi', default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='số người')),
                ('nganSach', models.FloatField(blank=True, db_column='nganSach', null=True, verbose_name='ngân sách')),
                ('chiPhiUocTinh', models.FloatField(blank=True, db_column='chiPhiUocTinh', null=True, verbose_name='chi phí ước tính')),
                ('trangThai', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_column='trangThai', default='draft', max_length=20, verbose_name='trạng thái')),
                ('laCongKhai', models.BooleanField(db_column='laCongKhai', default=False, verbose_name='là công khai')),
                ('soLuotXem', models.IntegerField(db_column='soLuotXem', default=0, verbose_name='số lượt xem')),
                ('soLuotThich', models.IntegerField(db_column='soLuotThich', default=0, verbose_name='số lượt thích')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
                ('lanCapNhatCuoi', models.DateTimeField(auto_now=True, db_column='lanCapNhatCuoi', verbose_name='lần cập nhật cuối')),
                ('chiTiet', models.TextField(blank=True, db_column='chiTiet', help_text='JSON string for day-by-day details', verbose_name='chi tiết (JSON)')),
            ],
            options={
                'verbose_name': 'Lịch trình',
                'verbose_name_plural': 'Lịch trình',
                'db_table': 'LICHTRINH',
                'ordering': ['-ngayTao'],
            },
        ),
        migrations.CreateModel(
            name='LichTrinhDiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayThamQuan', models.DateField(db_column='ngayThamQuan', verbose_name='ngày tham quan')),
                ('thoiGianThamQuan', models.CharField(blank=True, db_column='thoiGianThamQuan', help_text='e.g., "09:00-12:00"', max_length=50, verbose_name='thời gian tham quan')),
                ('thuTu', models.IntegerField(blank=True, db_column='thuTu', null=True, verbose_name='thứ tự')),
                ('ghiChu', models.TextField(blank=True, db_column='ghiChu', verbose_name='ghi chú')),
                ('chiPhiUocTinh', models.FloatField(blank=True, db_column='chiPhiUocTinh', null=True, verbose_name='chi phí ước tính')),
            ],
            options={
                'verbose_name': 'Lịch trình - Địa điểm',
                'verbose_name_plural': 'Lịch trình - Địa điểm',
                'db_table': 'LICHTRINH_DIADIEM',
                'ordering': ['ngayThamQuan', 'thuTu'],
            },
        ),
    ]
