# Generated by Django 5.0.1 on 2025-11-14 15:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LichTrinh',
            fields=[
                ('maLichTrinh', models.AutoField(db_column='maLichTrinh', primary_key=True, serialize=False)),
                ('tieuDe', models.CharField(db_column='tieuDe', max_length=255, verbose_name='tiêu đề')),
                ('moTa', models.TextField(blank=True, db_column='moTa', verbose_name='mô tả')),
                ('ngayBatDau', models.DateField(db_column='ngayBatDau', verbose_name='ngày bắt đầu')),
                ('ngayKetThuc', models.DateField(db_column='ngayKetThuc', verbose_name='ngày kết thúc')),
                ('soNgay', models.IntegerField(blank=True, db_column='soNgay', null=True, verbose_name='số ngày')),
                ('soNguoi', models.IntegerField(db_column='soNguoi', default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='số người')),
                ('nganSach', models.FloatField(blank=True, db_column='nganSach', null=True, verbose_name='ngân sách')),
                ('chiPhiUocTinh', models.FloatField(blank=True, db_column='chiPhiUocTinh', null=True, verbose_name='chi phí ước tính')),
                ('trangThai', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_column='trangThai', default='draft', max_length=20, verbose_name='trạng thái')),
                ('laCongKhai', models.BooleanField(db_column='laCongKhai', default=False, verbose_name='là công khai')),
                ('soLuotXem', models.IntegerField(db_column='soLuotXem', default=0, verbose_name='số lượt xem')),
                ('soLuotThich', models.IntegerField(db_column='soLuotThich', default=0, verbose_name='số lượt thích')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
                ('lanCapNhatCuoi', models.DateTimeField(auto_now=True, db_column='lanCapNhatCuoi', verbose_name='lần cập nhật cuối')),
                ('chiTiet', models.TextField(blank=True, db_column='chiTiet', help_text='JSON string for day-by-day details', verbose_name='chi tiết (JSON)')),
                ('maNguoiDung', models.ForeignKey(db_column='maNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='lich_trinhs', to=settings.AUTH_USER_MODEL, verbose_name='người dùng')),
                ('maTinhThanh', models.ForeignKey(blank=True, db_column='maTinhThanh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_trinhs', to='places.tinhthanh', verbose_name='tỉnh thành')),
            ],
            options={
                'verbose_name': 'Lịch trình',
                'verbose_name_plural': 'Lịch trình',
                'db_table': 'LICHTRINH',
                'ordering': ['-ngayTao'],
            },
        ),
        migrations.CreateModel(
            name='LichTrinhAI',
            fields=[
                ('maLichTrinhAI', models.AutoField(db_column='maLichTrinhAI', primary_key=True, serialize=False)),
                ('tieuDe', models.CharField(db_column='tieuDe', max_length=255, verbose_name='tiêu đề')),
                ('moTa', models.TextField(blank=True, db_column='moTa', verbose_name='mô tả')),
                ('ngayBatDau', models.DateField(blank=True, db_column='ngayBatDau', null=True, verbose_name='ngày bắt đầu')),
                ('ngayKetThuc', models.DateField(blank=True, db_column='ngayKetThuc', null=True, verbose_name='ngày kết thúc')),
                ('soNgay', models.IntegerField(blank=True, db_column='soNgay', null=True, verbose_name='số ngày')),
                ('soNguoi', models.IntegerField(blank=True, db_column='soNguoi', null=True, verbose_name='số người')),
                ('nganSach', models.FloatField(blank=True, db_column='nganSach', null=True, verbose_name='ngân sách')),
                ('trangThai', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('final', 'Final'), ('archived', 'Archived')], db_column='trangThai', default='generated', max_length=20, verbose_name='trạng thái')),
                ('chiTiet', models.TextField(blank=True, db_column='chiTiet', help_text='JSON string describing the generated schedule', verbose_name='chi tiết (JSON)')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
                ('lanCapNhatCuoi', models.DateTimeField(auto_now=True, db_column='lanCapNhatCuoi', verbose_name='lần cập nhật cuối')),
                ('maLichTrinh', models.ForeignKey(db_column='maLichTrinh', on_delete=django.db.models.deletion.CASCADE, related_name='ban_ai', to='itineraries.lichtrinh', verbose_name='lịch trình gốc')),
                ('maNguoiDung', models.ForeignKey(blank=True, db_column='maNguoiDung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_trinh_ai', to=settings.AUTH_USER_MODEL, verbose_name='người dùng')),
                ('maTinhThanh', models.ForeignKey(blank=True, db_column='maTinhThanh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_trinh_ai', to='places.tinhthanh', verbose_name='tỉnh thành')),
            ],
            options={
                'verbose_name': 'Lịch trình AI',
                'verbose_name_plural': 'Lịch trình AI',
                'db_table': 'LICHTRINHAI',
                'ordering': ['-ngayTao'],
            },
        ),
        migrations.CreateModel(
            name='LichTrinhAIDiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayThamQuan', models.DateField(blank=True, db_column='ngayThamQuan', null=True, verbose_name='ngày tham quan')),
                ('thoiGianThamQuan', models.CharField(blank=True, db_column='thoiGianThamQuan', help_text='e.g., "09:00-12:00"', max_length=50, verbose_name='thời gian tham quan')),
                ('thuTu', models.IntegerField(blank=True, db_column='thuTu', null=True, verbose_name='thứ tự')),
                ('ghiChu', models.TextField(blank=True, db_column='ghiChu', verbose_name='ghi chú')),
                ('chiPhiUocTinh', models.FloatField(blank=True, db_column='chiPhiUocTinh', null=True, verbose_name='chi phí ước tính')),
                ('maDiaDiem', models.ForeignKey(db_column='maDiaDiem', on_delete=django.db.models.deletion.CASCADE, related_name='lich_trinh_ai_dia_diems', to='places.diadiem', verbose_name='địa điểm')),
                ('maLichTrinhAI', models.ForeignKey(db_column='maLichTrinhAI', on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='itineraries.lichtrinhai', verbose_name='lịch trình AI')),
            ],
            options={
                'verbose_name': 'Lịch trình AI - Địa điểm',
                'verbose_name_plural': 'Lịch trình AI - Địa điểm',
                'db_table': 'LICHTRINHAI_DIADIEM',
                'ordering': ['ngayThamQuan', 'thuTu'],
                'unique_together': {('maLichTrinhAI', 'maDiaDiem', 'ngayThamQuan')},
            },
        ),
        migrations.AddField(
            model_name='lichtrinhai',
            name='dia_diems',
            field=models.ManyToManyField(related_name='lich_trinh_ai', through='itineraries.LichTrinhAIDiaDiem', to='places.diadiem'),
        ),
        migrations.CreateModel(
            name='LichTrinhDiaDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayThamQuan', models.DateField(db_column='ngayThamQuan', verbose_name='ngày tham quan')),
                ('thoiGianThamQuan', models.CharField(blank=True, db_column='thoiGianThamQuan', help_text='e.g., "09:00-12:00"', max_length=50, verbose_name='thời gian tham quan')),
                ('thuTu', models.IntegerField(blank=True, db_column='thuTu', null=True, verbose_name='thứ tự')),
                ('ghiChu', models.TextField(blank=True, db_column='ghiChu', verbose_name='ghi chú')),
                ('chiPhiUocTinh', models.FloatField(blank=True, db_column='chiPhiUocTinh', null=True, verbose_name='chi phí ước tính')),
                ('maDiaDiem', models.ForeignKey(db_column='maDiaDiem', on_delete=django.db.models.deletion.CASCADE, related_name='lich_trinh_dia_diems', to='places.diadiem', verbose_name='địa điểm')),
                ('maLichTrinh', models.ForeignKey(db_column='maLichTrinh', on_delete=django.db.models.deletion.CASCADE, related_name='lich_trinh_dia_diems', to='itineraries.lichtrinh', verbose_name='lịch trình')),
            ],
            options={
                'verbose_name': 'Lịch trình - Địa điểm',
                'verbose_name_plural': 'Lịch trình - Địa điểm',
                'db_table': 'LICHTRINH_DIADIEM',
                'ordering': ['ngayThamQuan', 'thuTu'],
            },
        ),
        migrations.AddField(
            model_name='lichtrinh',
            name='dia_diems',
            field=models.ManyToManyField(related_name='lich_trinhs', through='itineraries.LichTrinhDiaDiem', to='places.diadiem'),
        ),
        migrations.CreateModel(
            name='DongGop',
            fields=[
                ('maDongGop', models.AutoField(db_column='maDongGop', primary_key=True, serialize=False)),
                ('loaiDongGop', models.CharField(choices=[('them_dia_diem', 'Thêm địa điểm'), ('sua_thong_tin', 'Sửa thông tin'), ('bao_cao_loi', 'Báo cáo lỗi'), ('khac', 'Khác')], db_column='loaiDongGop', max_length=50, verbose_name='loại đóng góp')),
                ('noiDung', models.TextField(db_column='noiDung', verbose_name='nội dung')),
                ('trangThai', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_column='trangThai', default='pending', max_length=20, verbose_name='trạng thái')),
                ('phanHoi', models.TextField(blank=True, db_column='phanHoi', verbose_name='phản hồi')),
                ('ngayTao', models.DateTimeField(auto_now_add=True, db_column='ngayTao', verbose_name='ngày tạo')),
                ('ngayXuLy', models.DateTimeField(blank=True, db_column='ngayXuLy', null=True, verbose_name='ngày xử lý')),
                ('maDiaDiem', models.ForeignKey(blank=True, db_column='maDiaDiem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dong_gops', to='places.diadiem', verbose_name='địa điểm')),
                ('maNguoiDung', models.ForeignKey(db_column='maNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='dong_gops', to=settings.AUTH_USER_MODEL, verbose_name='người dùng')),
            ],
            options={
                'verbose_name': 'Đóng góp',
                'verbose_name_plural': 'Đóng góp',
                'db_table': 'DONGGOP',
                'ordering': ['-ngayTao'],
                'indexes': [models.Index(fields=['maNguoiDung', '-ngayTao'], name='DONGGOP_maNguoi_7b9582_idx'), models.Index(fields=['trangThai'], name='DONGGOP_trangTh_647d6c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lichtrinhai',
            index=models.Index(fields=['maNguoiDung', '-ngayTao'], name='LICHTRINHAI_maNguoi_74f04e_idx'),
        ),
        migrations.AddIndex(
            model_name='lichtrinhai',
            index=models.Index(fields=['maLichTrinh'], name='LICHTRINHAI_maLichT_2eadd0_idx'),
        ),
        migrations.AddIndex(
            model_name='lichtrinhai',
            index=models.Index(fields=['maTinhThanh'], name='LICHTRINHAI_maTinhT_fbeddd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lichtrinhdiadiem',
            unique_together={('maLichTrinh', 'maDiaDiem', 'ngayThamQuan')},
        ),
        migrations.AddIndex(
            model_name='lichtrinh',
            index=models.Index(fields=['maNguoiDung', '-ngayTao'], name='LICHTRINH_maNguoi_e409cb_idx'),
        ),
        migrations.AddIndex(
            model_name='lichtrinh',
            index=models.Index(fields=['ngayBatDau', 'ngayKetThuc'], name='LICHTRINH_ngayBat_e860e2_idx'),
        ),
        migrations.AddIndex(
            model_name='lichtrinh',
            index=models.Index(fields=['trangThai'], name='LICHTRINH_trangTh_6e6f96_idx'),
        ),
    ]
