# Generated by Django 5.0.1 on 2025-11-14 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichtrinh',
            name='maNguoiDung',
            field=models.ForeignKey(blank=True, db_column='maNguoiDung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lich_trinhs', to=settings.AUTH_USER_MODEL, verbose_name='người dùng'),
        ),
        migrations.AlterField(
            model_name='lichtrinh',
            name='maTinhThanh',
            field=models.ForeignKey(blank=True, db_column='maTinhThanh', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lich_trinhs', to='places.tinhthanh', verbose_name='tỉnh thành'),
        ),
        migrations.AlterField(
            model_name='lichtrinhai',
            name='maLichTrinh',
            field=models.ForeignKey(blank=True, db_column='maLichTrinh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban_ai', to='itineraries.lichtrinh', verbose_name='lịch trình gốc'),
        ),
        migrations.AlterField(
            model_name='lichtrinhai',
            name='maTinhThanh',
            field=models.ForeignKey(blank=True, db_column='maTinhThanh', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lich_trinh_ai', to='places.tinhthanh', verbose_name='tỉnh thành'),
        ),
    ]
