# Generated by Django 5.2.7 on 2025-10-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itineraries', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donggop',
            name='maDiaDiem',
            field=models.ForeignKey(blank=True, db_column='maDiaDiem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dong_gops', to='places.diadiem', verbose_name='địa điểm'),
        ),
    ]
