# Generated by Django 5.2.7 on 2025-10-29 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itineraries', '0002_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donggop',
            name='maNguoiDung',
            field=models.ForeignKey(db_column='maNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='dong_gops', to=settings.AUTH_USER_MODEL, verbose_name='người dùng'),
        ),
        migrations.AddField(
            model_name='lichtrinh',
            name='maNguoiDung',
            field=models.ForeignKey(db_column='maNguoiDung', on_delete=django.db.models.deletion.CASCADE, related_name='lich_trinhs', to=settings.AUTH_USER_MODEL, verbose_name='người dùng'),
        ),
        migrations.AddField(
            model_name='lichtrinhdiadiem',
            name='maDiaDiem',
            field=models.ForeignKey(db_column='maDiaDiem', on_delete=django.db.models.deletion.CASCADE, related_name='lich_trinh_dia_diems', to='places.diadiem', verbose_name='địa điểm'),
        ),
        migrations.AddField(
            model_name='lichtrinhdiadiem',
            name='maLichTrinh',
            field=models.ForeignKey(db_column='maLichTrinh', on_delete=django.db.models.deletion.CASCADE, related_name='lich_trinh_dia_diems', to='itineraries.lichtrinh', verbose_name='lịch trình'),
        ),
        migrations.AddField(
            model_name='lichtrinh',
            name='dia_diems',
            field=models.ManyToManyField(related_name='lich_trinhs', through='itineraries.LichTrinhDiaDiem', to='places.diadiem'),
        ),
        migrations.AddIndex(
            model_name='donggop',
            index=models.Index(fields=['maNguoiDung', '-ngayTao'], name='DONGGOP_maNguoi_7b9582_idx'),
        ),
        migrations.AddIndex(
            model_name='donggop',
            index=models.Index(fields=['trangThai'], name='DONGGOP_trangTh_647d6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lichtrinhdiadiem',
            unique_together={('maLichTrinh', 'maDiaDiem', 'ngayThamQuan')},
        ),
        migrations.AddIndex(
            model_name='lichtrinh',
            index=models.Index(fields=['maNguoiDung', '-ngayTao'], name='LICHTRINH_maNguoi_e409cb_idx'),
        ),
        migrations.AddIndex(
            model_name='lichtrinh',
            index=models.Index(fields=['ngayBatDau', 'ngayKetThuc'], name='LICHTRINH_ngayBat_e860e2_idx'),
        ),
        migrations.AddIndex(
            model_name='lichtrinh',
            index=models.Index(fields=['trangThai'], name='LICHTRINH_trangTh_6e6f96_idx'),
        ),
    ]
